# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.network :forwarded_port, guest: 8090, host: 8080, host_ip: "127.0.0.1"
  config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
  end
  config.vm.provision :shell, path: "setup.sh"
end
